# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a774ef0bc5fd4becffd0fb4af155b00a"
name = "Staging-Upsellify"
application_url = "https://participate-making-thought-candidate.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]  
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_orders,read_products,read_themes,write_discounts,write_orders,write_products"

[auth]
redirect_urls = [ "https://participate-making-thought-candidate.trycloudflare.com/api/auth" ]

[app_proxy]
url = "https://participate-making-thought-candidate.trycloudflare.com/apps/selleasy"
subpath = "selleasy"
prefix = "apps"
