# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aa010260b4fcd0578d275ce4e61d3682"
name = "Upsellify"
application_url = "https://pope-processes-refrigerator-springfield.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://pope-processes-refrigerator-springfield.trycloudflare.com/api/auth" ]
[app_proxy]
url = "https://pope-processes-refrigerator-springfield.trycloudflare.com/apps/selleasy"
subpath = "selleasy"
prefix = "apps"
